### ISSUE TITLE
@Stable VS @Immutable

### ISSUE THREAD

**Issue by hanchang97** [Team-BuddyCon/ANDROID_V2#12]
## 질문 내용
> 제목과 같이 두 어노테이션의 차이를 혹시 다들 어떤 방식으로 이해하고 계신지 궁금합니다..!
볼수록 혼동이 와서 질문드립니다

**Comment by ows3090** [comment]
@hanchang97 
저는 사용되는 예시로 주로 이해했던것 같아요
Immutable 어노테이션이 있는 클래스에서 프로퍼티들이 모두 val 이면 당연히 Immutable입니다.
하지만 간혹 val list : List<Int> 이런 경우가 있을 수가 있는데 List는 val로 선언했지만 MutableList가 대입될 수 있고
해당 값도 add, remove 가 가능하기 때문에 변경될 수가 있어요. 
이 때 Immutable 어노테이션을 사용하면 그 부분도 방지할 수 있다는 것 같아요

그리고 Stable은 변경은 가능하되 변경될 때마다 Compose 컴파일러가 관찰을 해서 변경사항이 없다면 리컴포지션을 발생하지 않고
변경이 있다면 리컴포지션 발생하게끔 하는 용도인 것 같아요
실제로 LazyListState가 Stable로 되어 있고 list의 position이 바뀌면 var 프로퍼티를 변경하도록 만들고 있을거에요

**Comment by ows3090** [comment]
@hanchang97 다시 헷갈리긴 하네요.. 혹시 다른 좋은 자료 있으면 공유 부탁드려요

**Comment by ows3090** [comment]
@hanchang97 https://www.youtube.com/watch?v=_FtKhWvHiTg 한번 참고해보세요~

**Comment by ows3090** [comment]
@hanchang97 일단 이슈는 종료할게요!
